package com.distributedComputingCA.protocol;

public enum Protocol {
    LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE, USER_ALREADY_LOGGED_IN, CREATE_USER, CREATE_USER_SUCCESS, CREATE_USER_FAILURE,
    DOWNLOAD, DOWNLOAD_SUCCESS, DOWNLOAD_FAILURE, UPLOAD, UPLOAD_SUCCESS, UPLOAD_FAILURE, LOGOFF, LOGOFF_SUCCESS,
    LOGOFF_FAILURE
}
