package com.distributedComputingCA.protocol;

public enum ServerProtocol {
	LOGIN_SUCCESS, LOGIN_FAILURE, USER_ALREADY_LOGGED_IN, CREATE_USER_SUCCESS, CREATE_USER_FAILURE, 
	DOWNLOAD_SUCCESS, DOWNLOAD_FAILURE, UPLOAD_SUCCESS, UPLOAD_FAILURE, LOGOFF_SUCCESS, LOGOFF_FAILURE
}
